//============================================================================
/// @file include_idl_2.idl
///
                                                           //qidl copyright
//% Copyright (c) 2012-2014, 2020 Qualcomm Technologies, Inc.
                                                           //qidl nested=false
//% All Rights Reserved.
//% Qualcomm Confidential and Proprietary
//============================================================================

#include "remote.idl"

interface include_idl_2 : remote_handle64 {
   #include "foo.idl"
   long sum(in sequence<long> vec);
   long func(in sequence<long> x);
   long sturct_func(in name n);
};
