//============================================================================
/// @file complex_sequence_2.idl
///
                                                           //qidl copyright
//% Copyright (c) 2023 Qualcomm Technologies, Inc.
                                                           //qidl nested=false
//% All Rights Reserved.
//% Qualcomm Confidential and Proprietary
//============================================================================

#include "remote.idl"

struct alpha{
  long x;
  sequence<long> l;
};

struct beta{
  long z;
  sequence<alpha> alp;
};

struct alpha1{
  long y;
  sequence<string> s;
};

struct beta1{
  sequence<alpha1> ss;
};

interface complex_sequence_2 : remote_handle64 {
  long method1(in sequence<beta> b, rout sequence<beta> b1);
  long method2(in sequence<beta1> B, rout sequence<beta1> B1);
};

